Repository monarch-initiative/mondo-ingest, pull requests merged in 2024-07, with the labels that each got.

#605 Update ODK `profile.txt` & fix build freezes
  src/ontology/profile.txt
Labels: bug

#616 OMIM: Annotated 'included' synonyms using a different property
  src/ontology/config/properties.txt
Labels: enhancement, omim

#603 Fix ODK version to 1.5.2
  src/ontology/run.sh.conf
Labels: stability
