Repository monarch-initiative/mondo-ingest, pull requests merged in 2024-06, with the labels that each got.

#521 Create `mondo-nando.sssom.tsv`
  src/mappings/mondo-nando.sssom.tsv
  src/mappings/nando-mondo.sssom.tsv
  src/ontology/external/nando-mappings.robot.owl
  src/ontology/external/nando-mappings.robot.tsv
  src/ontology/mondo-ingest.Makefile
  src/scripts/sssom_to_robot_template.py
Labels: enhancement, nando

#557 Bug fix: `pip-bioregistry`
  src/ontology/mondo-ingest.Makefile
Labels: bug

#562 update ordo exclusions
  src/ontology/config/ordo_exclusions.tsv
Labels: bug, orphanet / ordo

#559 HGNC robot template
  src/ontology/external/mondo-omim-genes.robot.owl
  src/ontology/external/mondo-omim-genes.robot.tsv
  src/ontology/mondo-ingest.Makefile
Labels: enhancement, omim, hgnc

#587 Delete: `check_me_out.sssom.tsv` (`develop`)
  src/scripts/lexmatch-sssom-compare.py
Labels: bug

#579 ODK `dev` --> `latest` (`develop`)
  src/ontology/run.sh.conf
Labels: enhancement

#551 Intelligently refresh `mondo.sssom.tsv` & `mondo.owl`
  src/ontology/mondo-ingest.Makefile
Labels: bug, productivity
