Repository monarch-initiative/mondo-ingest, pull requests merged in 2024-11, with the labels that each got.

#622 ODK 1.5.3 & Replace jinja2 with Jinjanator
  docs/odk-workflows/ManageDocumentation.md
  docs/odk-workflows/ReleaseWorkflow.md
  src/ontology/Makefile
  src/ontology/mondo-ingest.Makefile
  src/ontology/run.sh.conf
  src/sparql/class-count-by-prefix.sparql
Labels: enhancement

#671 Synonym sync: acronym case exception
  src/scripts/sync_synonym.py
Labels: enhancement

#705 Bug fix: Synonym sync tests
  tests/test_sync_synonym.py
Labels: bug, qc / test

#695 Bug fix: Synonym Sync: Entries without exact mappings
  src/scripts/sync_synonym.py
Labels: bug

#711 Delete duplicate variable declaration
  src/ontology/mondo-ingest.Makefile
  src/scripts/sync_subclassof.py
Labels: code quality

#681 Remove GARD
  .gitignore
  docs/odk-workflows/RepositoryFileStructure.md
  docs/reports/mapped_deprecated_gard.md
  docs/reports/migrate_gard.md
  docs/reports/unmapped_gard.md
  docs/sources/gard.md
  mkdocs.yaml
  src/ontology/Makefile
  src/ontology/config/gard_exclusions.tsv
  src/ontology/metadata/gard.yml
  src/ontology/mondo-ingest-odk.yaml
  src/ontology/mondo-ingest.Makefile
  src/ontology/reports/component_signature-gard.tsv
  src/ontology/reports/gard_excluded_terms_in_mondo_xrefs.tsv
  src/ontology/reports/gard_excluded_terms_in_mondo_xrefs_summary.tsv
  src/ontology/reports/gard_exclusion_reasons.robot.template.tsv
  src/ontology/reports/gard_mapped_deprecated_terms.robot.template.tsv
  src/ontology/reports/gard_mapping_status.tsv
  src/ontology/reports/gard_term_exclusions.txt
  src/ontology/reports/gard_unmapped_terms.tsv
  src/ontology/reports/mirror_signature-gard.tsv
  src/ontology/slurp/gard.tsv
  src/ontology/unmapped/gard-unmapped.owl
  src/sparql/gard-relevant-signature.sparql
Labels: code quality

#692 Synonym Sync - unsilence a goal
  src/ontology/mondo-ingest.Makefile
Labels: stability
