Repository monarch-initiative/mondo-ingest, pull requests merged in 2024-08, with the labels that each got.

#600 Exact synonym updates
  src/ontology/config/property-map.sssom.tsv
  src/ontology/mondo-ingest.Makefile
  src/sparql/exact_syn_from_label.ru
Labels: enhancement

#613 Ensure that exact synonyms in NCIT are preserved
  src/ontology/mondo-ingest.Makefile
Labels: bug, ncit

#642 Problematic exclusions codestyle updates
  src/analysis/problematic_exclusions.py
  src/ontology/mondo-ingest.Makefile
Labels: code quality

#594 Refactor git refresh system (small refactor)
  src/ontology/mondo-ingest.Makefile
Labels: code quality

#646 Add draft reference for excluded values
  src/ontology/config/mondo-excluded-values.yml
Labels: enhancement
