Repository monarch-initiative/mondo-ingest, pull requests merged in 2025-02, with the labels that each got.

#751 Address `qc-duplicate-exact-synonym-no-abbrev` failures in `mondo`
  src/ontology/mondo-ingest.Makefile
  src/scripts/sync_synonym.py
  src/scripts/sync_synonym_curation_filtering.py
  src/sparql/synonyms-scope-type-xref.sparql
Labels: bug

#772 Bug fix: `ModuleNotFoundError`
  src/scripts/sync_synonym_curation_filtering.py
Labels: bug

#775 Bug fix: `KeyError` on `mondo_label`
  src/sparql/synonyms-scope-type-xref.sparql
Labels: bug

#728 ODK upgrade && `odkrunner`
  README.md
  docs/odk-workflows/ManageDocumentation.md
  docs/odk-workflows/ReleaseWorkflow.md
  src/ontology/Makefile
  src/ontology/run.sh.conf
Labels: enhancement

#789 run mondo-omim-genes.robot.tsv goal to get new omim file content
  src/ontology/external/mondo-omim-genes.robot.tsv
Labels: artefact-updates

#783 Synonym Sync: DO `-added` filtering
  src/ontology/mondo-ingest.Makefile
  src/scripts/sync_synonym.py
Labels: artefact-updates
